In [7]:
import numpy as np
from pprintpp import pprint as pp


In [8]:
a = np.array([[0, 0, 0], [1, 0, -1], [0, -1, 1]])

a

array([[ 0,  0,  0],
       [ 1,  0, -1],
       [ 0, -1,  1]])

In [33]:
for x in a:
    y = list(x)
    y = [str(n) for n in y]
    print('|'+'|'.join(list(y)).replace('-1', '  O  ').replace('1', '  X  ').replace('0', ' 0,1 ')+'|')

| 0,1 | 0,1 | 0,1 |
|  X  | 0,1 |  O  |
| 0,1 |  O  |  X  |


In [45]:
len(np.where(a==3)[0])
# list(zip(*[x.tolist() for x in np.where(a==1)]))
# list(zip(x.tolist() for x in np.where(a==1)))

0

In [35]:
player_positions = list(zip(*[x.tolist() for x in np.where(a==1)]))

win_positions = [[[1, 1], [0, 1]], [[1, 0], [2, 2]]]
win_positions = [[tuple(x) for x in y] for y in win_positions] # convert (list of list of lists) to (list of list of tuples)
print(win_positions)

for win_combo in win_positions:
    print(set(win_combo).issubset(player_positions))

[[(1, 1), (0, 1)], [(1, 0), (2, 2)]]
False
True


In [37]:
[[0]*3]*3

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [40]:
PLAYERS = {
    'player_1': {
        'player_num': 1
        , 'board_value': 1
    }
    , 'player_2': {
        'player_num': 2
        , 'board_value': -1
    }
}

PLAYERS['player_1']['board_value']

1

In [51]:
('left' in ['left', 'right', 'up']) and ('right' in ['left', 'right', 'up'])

True

In [72]:
TOP_ROW_INDX = 'top_row_indx'
BOTTOM_ROW_INDX = 'bottom_row_indx'
LEFT_COLUMN_INDX = 'left_column_indx'
RIGHT_COLUMN_INDX = 'right_column_indx'

def is_in_outer_perimeter(outer_perimeter, row, column):
    return (
        (
            (row in [outer_perimeter[TOP_ROW_INDX], outer_perimeter[BOTTOM_ROW_INDX]])
        )
        or 
        (
            (column in [outer_perimeter[LEFT_COLUMN_INDX], outer_perimeter[RIGHT_COLUMN_INDX]])
        )
    )

outer_perimeter = {
    TOP_ROW_INDX: 0
    , BOTTOM_ROW_INDX: 3
    , LEFT_COLUMN_INDX: 0
    , RIGHT_COLUMN_INDX: 4
}

outer_perimeter_positions = []
for row in range(outer_perimeter[TOP_ROW_INDX], outer_perimeter[BOTTOM_ROW_INDX] + 1):
    for column in range(outer_perimeter[LEFT_COLUMN_INDX], outer_perimeter[RIGHT_COLUMN_INDX] + 1):
        if is_in_outer_perimeter(outer_perimeter, row, column):
            outer_perimeter_positions.append((row, column))

z = np.array([[0]*5]*4)
for p in outer_perimeter_positions:
    z[p[0], p[1]] = 1
pp(z)
pp(outer_perimeter_positions)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])
[
    (0, 0),
    (0, 1),
    (0, 2),
    (0, 3),
    (0, 4),
    (1, 0),
    (1, 4),
    (2, 0),
    (2, 4),
    (3, 0),
    (3, 1),
    (3, 2),
    (3, 3),
    (3, 4),
]


In [63]:
for x in range(0, 3):
    print(x)

0
1
2


In [8]:
Position(1, 2)
print(Position(1, 2))

[1, 2]


In [1]:
from classes.player import Player

In [2]:
p1 = Player(1, 1)
print(p1)

Player(player_num: 1, board_value: 1)


In [3]:
p1.opponent = Player(3 - p1.player_num, (-1) * p1.board_value)
print(p1)

Player(player_num: 1, board_value: 1, opponent: Player(player_num: 2, board_value: -1))


In [4]:
p1.opponent

In [4]:
p2 = p1.opponent
p2

Player(player_num: 2, board_value: -1)

In [5]:
p2.opponent = p1
print(p2)

RecursionError: maximum recursion depth exceeded while calling a Python object

In [1]:
import numpy as np
from board import Board

In [2]:
%load_ext autoreload
%autoreload 2

In [10]:
Board(rows=4, columns=5, board_positions=np.array([[0, 0, 0, 0, 0],
    [0, 0, -1, 0, 0],
    [0, 0, -1, 0, 0],
    [1, 0, 1, 0, 0]]))


     |  0  |  1  |  2  |  3  |  4  |
0    |     |     |     |     |     |
1    |     |     |  O  |     |     |
2    |     |     |  O  |     |     |
3    |  X  |     |  X  |     |     |

In [21]:
print(Board(rows=4, columns=5, board_positions=np.array([[0, 0, 0, 0, 0],
    [0, 0, -1, 0, 0],
    [0, 0, -1, 0, 0],
    [1, 0, 1, 0, 0]])))

     |  0  |  1  |  2  |  3  |  4  |
------------------------------------
0    |     |     |     |     |     |
-----|  -  |  -  |  -  |  -  |  -  |
1    |     |     |  O  |     |     |
-----|  -  |  -  |  -  |  -  |  -  |
2    |     |     |  O  |     |     |
-----|  -  |  -  |  -  |  -  |  -  |
3    |  X  |     |  X  |     |     |
-----|  -  |  -  |  -  |  -  |  -  |
------------------------------------


In [22]:
print('''
     |  0  |  1  |  2  |  3  |  4  |
------------------------------------
0    |  X  |  X  |  X  |  X  |  X  |
-----|  -  |  -  |  -  |  -  |  -  |
1    |  X  |     |  O  |     |  X  |
-----|  -  |  -  |  -  |  -  |  -  |
2    |  X  |     |  O  |     |  X  |
-----|  -  |  -  |  -  |  -  |  -  |
3    |  X  |  X  |  X  |  X  |  X  |
-----|  -  |  -  |  -  |  -  |  -  |
------------------------------------
''')


     |  0  |  1  |  2  |  3  |  4  |
------------------------------------
0    |  X  |  X  |  X  |  X  |  X  |
-----|  -  |  -  |  -  |  -  |  -  |
1    |  X  |     |  O  |     |  X  |
-----|  -  |  -  |  -  |  -  |  -  |
2    |  X  |     |  O  |     |  X  |
-----|  -  |  -  |  -  |  -  |  -  |
3    |  X  |  X  |  X  |  X  |  X  |
-----|  -  |  -  |  -  |  -  |  -  |
------------------------------------



In [10]:
print(''.join(['-' for x in Board().get_separator_line()]))
print(Board())


------------------------
     |  0  |  1  |  2  |
________________________

0    |     |     |     |
________________________

1    |     |     |     |
________________________

2    |     |     |     |
________________________



In [23]:
a = input('what move do you want to play?')

In [25]:
print(a)

type(a)

1,2


str

In [36]:
games = {1: 1, 2: -1, 3: 1, 4: 9}
max(games.values())

9

In [37]:
len([x for x in games.values() if x == 1])

2

In [38]:
(1, 2) in list(zip(*[x.tolist() for x in np.where(Board().board_positions == 0)]))

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [39]:
(1, 2) in list(zip(*[x.tolist() for x in np.where(Board().board_positions == 0)]))

True

In [41]:
a = Board()
print(a.get_valid_moves())

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]


In [45]:
m = ',' in 'blahsdf'

m

False

In [46]:
int('a')

ValueError: invalid literal for int() with base 10: 'a'

In [48]:
[x for x in {}.values()]

[]

In [53]:
len(np.where(Board().board_positions == 1)[0])

0

In [61]:
from config import WIN_COMBOS

a = Board(board_positions = np.array([[0, 0, 0], [1, 0, -1], [1, 1, 1]]), win_combos=WIN_COMBOS)
a.player_to_act = "player_1"
a.check_game_status()

1

In [1]:
from anytree import NodeMixin, RenderTree

In [3]:
from copy import deepcopy
from math import log, sqrt
import numpy as np
from config import (
    EXPLORATION_CONSTANT,
    ROWS
    , COLUMNS
    , NUM_CONSECUTIVE_FOR_WIN
    , PLAYER_1
    , PLAYER_2
    , PLAYER_NUM
    , BOARD_VALUE
    , BOARD_STR
    , PLAYERS
    , WIN_COMBOS
    , DRAW_STATUS
    , ONGOING_GAME_STATUS
    , PLAYER_1_WIN_STATUS
    , PLAYER_2_WIN_STATUS
    , OPPONENT
)

class Board2(NodeMixin):

    def __init__(
        self
        , rows = ROWS
        , columns = COLUMNS
        , num_consecutive_for_win = NUM_CONSECUTIVE_FOR_WIN
        , board_positions = None
        , player_to_act = None
        , win_combos = WIN_COMBOS
        , parent = None
        , children = None
    ):
        super().__init__()
        self.rows = rows
        self.columns = columns
        self.board_shape = [self.rows, self.columns]
        self.num_consecutive_for_win = num_consecutive_for_win
        if board_positions is None:
            board_positions = np.array([[0] * self.columns] * self.rows)
        self.board_positions = board_positions
        self.player_to_act = player_to_act
        self.win_combos = win_combos
        self.parent = parent
        if children:
            self.children
    
    def get_separator_line(self):
        return ['-']*(self.columns*6 + 6)


    def convert_row_to_print_string(
        self
        , row
        , row_indx
    ):
        return (
            f"{str(row_indx).ljust(5, ' ')}" +
            '|' + 
            (
                '|'\
                .join(row)\
                .replace(str(PLAYERS[PLAYER_2][BOARD_VALUE]), f'  {PLAYERS[PLAYER_2][BOARD_STR]}  ')\
                .replace(str(PLAYERS[PLAYER_1][BOARD_VALUE]), f'  {PLAYERS[PLAYER_1][BOARD_STR]}  ')\
                .replace('0', '     ')
            ) +
            '|\n' +
            '-----|' + 
            (
                '|'\
                .join(row)\
                .replace(str(PLAYERS[PLAYER_2][BOARD_VALUE]), '  -  ')\
                .replace(str(PLAYERS[PLAYER_1][BOARD_VALUE]), '  -  ')\
                .replace('0', '  -  ')
            ) +
            '|'
        )


    def get_board_string(self):
        
        board_header = (
            '     |' +
            "|".join([f'  {str(column_indx)}  ' for column_indx in range(self.columns)]) +
            '|\n' +
            ''.join(self.get_separator_line())
        )
        
        board_strings = [board_header]
        for row_indx, row in enumerate(self.board_positions):
            row = [str(x) for x in row]
            board_strings.append(self.convert_row_to_print_string(row, row_indx))
        
        board_footer = ''.join(self.get_separator_line())
        board_strings.append(board_footer)
        
        return '\n'.join(board_strings)


    def __repr__(self):
        return self.get_board_string()


    def __str__(self):
        return self.get_board_string()

In [8]:
from classes import Board

a = Board()

In [13]:
available_indices = list(zip(*[indx.tolist() for indx in np.where(a.board_positions==0)]))
available_moves = []
for available_move in available_indices:
    new_state = a.board_positions.copy()
    row_index = available_move[0]
    column_index = available_move[1]
    new_state[row_index, column_index] = 1


[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
(0, 0)
[[1 0 0]
 [0 0 0]
 [0 0 0]]
(0, 1)
[[0 1 0]
 [0 0 0]
 [0 0 0]]
(0, 2)
[[0 0 1]
 [0 0 0]
 [0 0 0]]
(1, 0)
[[0 0 0]
 [1 0 0]
 [0 0 0]]
(1, 1)
[[0 0 0]
 [0 1 0]
 [0 0 0]]
(1, 2)
[[0 0 0]
 [0 0 1]
 [0 0 0]]
(2, 0)
[[0 0 0]
 [0 0 0]
 [1 0 0]]
(2, 1)
[[0 0 0]
 [0 0 0]
 [0 1 0]]
(2, 2)
[[0 0 0]
 [0 0 0]
 [0 0 1]]
